<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1527393357786" stop="1527393357864">
  <name>test_01</name>
  <labels/>
  <test-cases>
    <test-case start="1527393357786" status="passed" stop="1527393357801">
      <name>Test_01.test_a[1]</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="6468-MainThread"/>
        <label name="host" value="LAPTOP-L839SAPQ"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1527393357801" status="failed" stop="1527393357864">
      <name>Test_01.test_a[2]</name>
      <failure>
        <message>AssertionError: assert 2 != 2</message>
        <stack-trace>self = &lt;test_01.Test_01 object at 0x0591ECF0&gt;, a = 2

    @pytest.mark.parametrize("a",[1,2,3])
    def test_a(self, a):
&gt;       assert a != 2
E       assert 2 != 2

scripts\test_01.py:5: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="6468-MainThread"/>
        <label name="host" value="LAPTOP-L839SAPQ"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1527393357864" status="passed" stop="1527393357864">
      <name>Test_01.test_a[3]</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="6468-MainThread"/>
        <label name="host" value="LAPTOP-L839SAPQ"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
